In [58]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [61]:
def mat_factorization(mat, user_features, item_features, features, epoch=100, alpha=0.002, beta=0.02):
    for val in tqdm(range(epoch)):
      for value in range(len(mat)):
          for values in range(len(mat[value])):
              if mat[value][values] > 0:
                  error_mat = mat[value][values] - np.dot(user_features[value,:], item_features[:, values]) # To find the error between the original given matrix and the matrices obtained from the rand function.

                  for data in range(features):
                      user_features[value][data] = user_features[value][data] + alpha * (2 * item_features[data][values] * error_mat - beta * user_features[value][data]) # Using the gradient descent function to reduce the error between matrices
                      item_features[data][values] = item_features[data][values] + alpha * (2 * user_features[value][data] * error_mat - beta * item_features[data][values])

    return user_features, item_features.T

In [34]:
rating = pd.read_csv("ratings.csv")
link = pd.read_csv("links.csv")
g_tags = pd.read_csv("genome-tags.csv")
g_scores = pd.read_csv("genome-scores.csv")
tag = pd.read_csv("tags.csv")
movie = pd.read_csv("movies.csv")

In [35]:
print(rating)
rating.shape

          userId  movieId  rating   timestamp
0              1        2     3.5  1112486027
1              1       29     3.5  1112484676
2              1       32     3.5  1112484819
3              1       47     3.5  1112484727
4              1       50     3.5  1112484580
...          ...      ...     ...         ...
20000258  138493    68954     4.5  1258126920
20000259  138493    69526     4.5  1259865108
20000260  138493    69644     3.0  1260209457
20000261  138493    70286     5.0  1258126944
20000262  138493    71619     2.5  1255811136

[20000263 rows x 4 columns]


(20000263, 4)

In [15]:
movie

movieId  ...                                       genres
0            1  ...  Adventure|Animation|Children|Comedy|Fantasy
1            2  ...                   Adventure|Children|Fantasy
2            3  ...                               Comedy|Romance
3            4  ...                         Comedy|Drama|Romance
4            5  ...                                       Comedy
...        ...  ...                                          ...
27273   131254  ...                                       Comedy
27274   131256  ...                                       Comedy
27275   131258  ...                                    Adventure
27276   131260  ...                           (no genres listed)
27277   131262  ...                     Adventure|Fantasy|Horror

[27278 rows x 3 columns]

In [36]:
movie_rating = pd.merge(rating, movie, on='movieId')
movie_rating

userId  ...                      genres
0              1  ...  Adventure|Children|Fantasy
1              5  ...  Adventure|Children|Fantasy
2             13  ...  Adventure|Children|Fantasy
3             29  ...  Adventure|Children|Fantasy
4             34  ...  Adventure|Children|Fantasy
...          ...  ...                         ...
20000258  138301  ...                Comedy|Crime
20000259  138301  ...      Action|Comedy|Thriller
20000260  138301  ...                   Drama|War
20000261  138406  ...                 Crime|Drama
20000262  138406  ...                   Film-Noir

[20000263 rows x 6 columns]

In [37]:
movie_rating['userId'].unique()

array([     1,      5,     13, ...,  40432,    861, 121610])

In [38]:
movie_rating = movie_rating.iloc[:1000000]

In [39]:
movie_rating

userId  ...                      genres
0            1  ...  Adventure|Children|Fantasy
1            5  ...  Adventure|Children|Fantasy
2           13  ...  Adventure|Children|Fantasy
3           29  ...  Adventure|Children|Fantasy
4           34  ...  Adventure|Children|Fantasy
...        ...  ...                         ...
999995   90990  ...            Action|Adventure
999996   90991  ...            Action|Adventure
999997   90995  ...            Action|Adventure
999998   90997  ...            Action|Adventure
999999   90998  ...            Action|Adventure

[1000000 rows x 6 columns]

In [40]:
movie_rating['title'].unique()

array(['Jumanji (1995)',
       'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
       'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
       'Seven (a.k.a. Se7en) (1995)', 'Usual Suspects, The (1995)',
       'Rumble in the Bronx (Hont faan kui) (1995)', 'Rob Roy (1995)',
       'Clerks (1994)',
       'Interview with the Vampire: The Vampire Chronicles (1994)',
       'Star Wars: Episode IV - A New Hope (1977)',
       'Léon: The Professional (a.k.a. The Professional) (Léon) (1994)',
       'Pulp Fiction (1994)', 'Shawshank Redemption, The (1994)',
       "What's Eating Gilbert Grape (1993)", 'Mask, The (1994)',
       'Blade Runner (1982)', 'Terminator 2: Judgment Day (1991)',
       'Silence of the Lambs, The (1991)', 'Dragonheart (1996)',
       'Wizard of Oz, The (1939)', '2001: A Space Odyssey (1968)',
       'Escape to Witch Mountain (1975)', 'Die Hard (1988)',
       'Fish Called Wanda, A (1988)',
       "Monty Python's Life of Brian (1979)", 'Reservoir Dogs (1

In [41]:
matrix = movie_rating.pivot_table(values='rating', index='userId', columns='title').fillna(0.0)
matrix

title   2001: A Space Odyssey (1968)  ...  Wizard of Oz, The (1939)
userId                                ...                          
1                                3.5  ...                       3.5
2                                5.0  ...                       0.0
3                                5.0  ...                       4.0
4                                0.0  ...                       0.0
5                                0.0  ...                       0.0
...                              ...  ...                       ...
138488                           0.0  ...                       0.0
138489                           0.0  ...                       0.0
138490                           0.0  ...                       0.0
138492                           0.0  ...                       0.0
138493                           0.0  ...                       0.0

[125917 rows x 32 columns]

In [42]:
matrix = matrix.values
matrix

array([[3.5, 4. , 3.5, ..., 3.5, 3.5, 3.5],
       [5. , 5. , 0. , ..., 0. , 0. , 0. ],
       [5. , 5. , 0. , ..., 5. , 3. , 4. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 3. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 4. , 0. ]])

In [62]:
features = 3
user_features = np.random.rand(len(matrix), features) # Initializing the user and item matrix using the np.random.rand function.
item_features = np.random.rand(features, len(matrix[0]))
user_mat, item_mat = mat_factorization(matrix, user_features, item_features, features)

100%|██████████| 100/100 [45:02<00:00, 27.02s/it]


In [63]:
final_mat = np.dot(user_mat, item_mat.T)
final_mat

array([[3.58031766, 3.74455408, 3.77347425, ..., 3.85962192, 3.46083621,
        4.01243069],
       [4.88608066, 4.98109972, 4.68060876, ..., 5.04041946, 4.28004941,
        4.68810933],
       [4.42670019, 4.53580966, 4.42483889, ..., 4.86922357, 4.38058795,
        4.40331108],
       ...,
       [4.01942315, 4.15796389, 4.13720249, ..., 4.42823643, 4.01219493,
        4.23528818],
       [4.22772403, 4.34484995, 4.14656135, ..., 4.34389882, 3.69589721,
        4.26474347],
       [4.18405621, 4.39586655, 4.54101472, ..., 4.69913866, 4.36119241,
        4.81940349]])

In [64]:
pd.DataFrame(user_mat).to_csv('user_mat.csv')
pd.DataFrame(item_mat).to_csv('item_mat.csv')
pd.DataFrame(final_mat).to_csv('final_mat.csv')

In [66]:
final_mat.shape

(125917, 32)

In [70]:
final_values = pd.DataFrame(final_mat, index=movie_rating['userId'].unique(), columns=movie_rating['title'].unique())
final_values

Jumanji (1995)  ...  Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
1            3.580318  ...                                           4.012431                             
5            4.886081  ...                                           4.688109                             
13           4.426700  ...                                           4.403311                             
29           2.761770  ...                                           2.773039                             
34           4.612947  ...                                           4.724331                             
...               ...  ...                                                ...                             
90326        2.751317  ...                                           3.344458                             
90543        3.780333  ...                                           4.373232                             
90763        4.019423  ...                                           4.235288                             
90766        4.227724  ...                                           4.264743                             
90916        4.184056  ...                                           4.819403                             

[125917 rows x 32 columns]

In [77]:
user_id = int(input("Enter the user Id to find the predictions"))
final_values.iloc[user_id]

Enter the user Id to find the predictions55


Jumanji (1995)                                                                    3.771200
City of Lost Children, The (Cité des enfants perdus, La) (1995)                   3.859477
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)                                         3.621456
Seven (a.k.a. Se7en) (1995)                                                       3.085860
Usual Suspects, The (1995)                                                        3.854713
Rumble in the Bronx (Hont faan kui) (1995)                                        3.485666
Rob Roy (1995)                                                                    3.451320
Clerks (1994)                                                                     2.762491
Interview with the Vampire: The Vampire Chronicles (1994)                         3.445323
Star Wars: Episode IV - A New Hope (1977)                                         3.231099
Léon: The Professional (a.k.a. The Professional) (Léon) (1994)                    3.138976